cursor #dee3e6
cursor_text_color #c0c8cc

foreground            #dee3e6
background            #0f1417
selection_foreground  #1e333c
selection_background  #b4cad5
url_color             #8ad0ee

color0   #0f1417
color1   #ff72a0
color2   #77ee84
color3   #fff672
color4   #70bfe2
color5   #19546e
color6   #8ad0ee
color7   #eaf5f9
color8   #8f979a
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #a3e3ff
color13  #b3e8ff
color14  #cef0ff
color15  #f8fdff
