font_family				Iosevka NF
font_size				14.0
bold_font				auto
italic_font				auto
bold_italic_font		auto

cursor_shape beam
cursor_beam_thickness	1.5
cursor_blink_interval	0.5
cursor_trail 1

window_padding_width	10
background_opacity		1.0

confirm_os_window_close 0
allow_remote_control	yes
listen_on               unix:/tmp/kitty-{kitty_pid}

# make it behave like alacritty
map ctrl+shift+b show_scrollback
terminal_select_modifiers shift
map ctrl+minus change_font_size all -2.0
map ctrl+equal change_font_size all +2.0
map ctrl+0 change_font_size all 0
enable_audio_bell no
close_on_child_death yes

include ~/.config/kitty/dank-theme.conf
include ~/.config/kitty/dank-tabs.conf
