#!/bin/bash

title="theme:"

typeset -A menu
menu=(
    [Cysis]="switch-theme cysis"
    [Nyt]="switch-theme nyt"
	[Nord]="switch-theme nord"
	[Korean]="switch-theme korean"
	[Japan]="switch-theme japan"
)

