#! /bin/sh
###--Close these programs---###
killall -q sxhkd dunst picom greenclip polybar discord-rpc-status pidswallow touchegg bash kdeconnectd

###---Fix Cursor---###
xsetroot -cursor_name left_ptr &
xset +dpms dpms 60 60 60 &

###---Theme!---###
# This needs to be done before the pbstart and cannot be done asynchronesly.
wal -q -R

###---Autostart---###
$(mkfifo /tmp/sfifo; sxhkd -s /tmp/sfifo) &
picom -b
greenclip daemon &
kdeconnectd &
skippy-xd --start-daemon &

## Polybar ##
pbstart
[[ $POLYBAR_BAR = "top" ]] &&  hideIt.sh --name '^polybar-top_eDP' --hover -d top -p 1 --wait &

###---Touchpad---###
touchegg &

##--Terminal Swallowing--##
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -fl 'pidswallow -V -gl' || pidswallow -V -gl & # Terminal swallowing

###---BSPWM---###
bspc monitor primary -d 1 2 3 4 5 6

bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config ignore_ewmh_focus on
# bspc config ignore_ewmh_struts false
bspc config swallow_first_click false

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color1"

###---Rules---###
# Open on specific workspace

X=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1 | head -1)
Y=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | head -1)

X2=$[X/2]
Y2=$[Y/2]

X3=$[X/3]
Y3=$[Y/3]

X4=$[X/4]
Y4=$[Y/4]

bspc rule -a FloatingSmall state=floating rectangle=${X3}x${Y3}+${X3}+0 sticky=on
# bspc rule -a FloatingMedium state=floating rectangle=${X2}x${Y2}+${X4}+${Y4} sticky=on
bspc rule -a FloatingMedium state=floating rectangle=$[X2+400]x$[Y2+200]+$[X4-200]+$[Y4-100] sticky=on
bspc rule -a FloatingSide state=floating rectangle=${X2}x${Y2}+${X4}+${Y2} sticky=on
bspc rule -a Connman-gtk state=floating
bspc rule -a iwgtk state=floating
bspc rule -a xkcd state=floating

bspc rule -a Brave-browser desktop=1
bspc rule -a Code desktop=2
bspc rule -a Vivaldi-stable desktop=3
bspc rule -a obsidian desktop=4

# NEW Scratchpad windows (scratchpad-workspace)
bspc rule -a vesktop desktop=6 
bspc rule -a Vivaldi-stable:web.whatsapp.com desktop=6
bspc rule -a com.github.th_ch.youtube_music desktop=6
bspc rule -a Spotify desktop=6
bspc rule -a discord desktop=6

# Picture in Picture
bspc rule -a zen:Toolkit:Picture-in-Picture sticky=on state=floating rectangle=212x119+0+961

# Open applications
pgrep zen || $BROWSER &
pgrep vivaldi || vivaldi-stable --app="https://web.whatsapp.com" &
pgrep spotify || spotify &
