#! /bin/sh

###--Close these programs---###
killall -q sxhkd xss-lock dunst picom greenclip kdeconnectd polybar discord-rpc-status

###---SXKHD---###
sxhkd &

###---Fix Cursor---###
xsetroot -cursor_name left_ptr &

##---Fix Displays---###
exec ~/.screenlayout/fix.sh &

###---Autostart---###
wal -R
#xautolock -time "10" -locker "blurlock" -notify "10" -notifier "dunst" -killtime "10" -killer "systemctl suspend" -detectsleep &
#alacritty --class="Startup" &
dunst &
picom -b &
#exec ~/.fehbg &
pbstart &
greenclip daemon &
#exec /usr/lib/kdeconnectd &

LD_LIBRARY_PATH=~/Documents/DiscordRPC/lib exec ~/Documents/DiscordRPC/discord-rpc-status &

###---BSPWM---###
bspc monitor -d 1 2 3 4 5

bspc config border_width 		2
bspc config window_gap 			20

bspc config split_ratio 		0.52
bspc config borderless_monocle 	false
bspc config gapless_monocle 	false

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true

bspc config ignore_ewmh_focus on

###---Theme!---###

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color5"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

###---Rules---###

# Open on specific workspace
bspc rule -a qutebrowser desktop=1
#bspc rule -a Alacritty desktop=2
#bspc rule -a discord desktop=3
#bspc rule -a Element desktop=3
#bspc rule -a minecraft-launcher desktop=4
#bspc rule -a Minecraft\ 1.16.5 desktop=4

bspc rule -a Alacritty:Alsamixer state=floating rectangle=600x300+383+234
bspc rule -a Alacritty:Startup state=floating rectangle=600x300+383+234
bspc rule -a Alacritty:Music state=floating rectangle=600x300+383+234
bspc rule -a Connman-gtk state=floating
bspc rule -a discord state=floating rectangle=1362x384+0+380 sticky=on layer=above
