#! /bin/sh

###--Close these programs---###
killall -q sxhkd dunst picom greenclip polybar discord-rpc-status pidswallow

##---Fix Displays---###
xcalib ~/.config/display_calibration.icm
#./.screenlayout something I don't remember

###---Fix Cursor---###
xsetroot -cursor_name left_ptr &

###---Theme!---###
# This needs to be done before the pbstart and cannot be done asynchronesly.
wal -q -R

###---Autostart---###
$(
	mkfifo /tmp/sfifo
	sxhkd -s /tmp/sfifo
) & # For the polybar module to detect whether sxhkd is in chain mode
#dunst-start & # no need to start dunst, it autostarts anyways
#picom --experimental-backends -b &
picom -b # no & cause we want picom to start properly first and then start polybar so shadows work along with ftlabs' animations
pbstart &
greenclip daemon &

###---Touchpad---###
libinput-gestures-setup restart &

##--Terminal Swallowing--##
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -fl 'pidswallow -V -gl' || pidswallow -V -gl & # Terminal swallowing

###---Discord RPC---###
LD_LIBRARY_PATH=~/Documents/DiscordRPC/lib exec ~/Documents/DiscordRPC/discord-rpc-status &

###---Fix Audio---###
#amixer -D hw:1 sset Master 50% -q &

###---BSPWM---###
bspc monitor -d 1 2 3 4 5
#bspc monitor ^2 -d 6 7

bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

# Master stack layout experiment
#bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child
#bspc config removal_adjustment true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus on

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color1"

###---Rules---###
# Open on specific workspace

X=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1 | head -1)
Y=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | head -1)

X2=$[X/2]
Y2=$[Y/2]

X3=$[X/3]
Y3=$[Y/3]

X4=$[X/4]
Y4=$[Y/4]

# Oneshots, only apply to the first window
bspc rule -a Vivaldi-stable -o desktop=1
bspc rule -a Alacritty -o desktop=2

#bspc rule -a Youtube\ Music state=floating rectangle=${X2}x${Y2}+${X4}+${Y4}
bspc rule -a Vivaldi-stable:web.whatsapp.com state=floating rectangle=${X2}x${Y2}+${X4}+${Y4} layer=above
bspc rule -a YouTube\ Music:\* state=floating rectangle=${X2}x${Y2}+${X4}+${Y4} layer=above
bspc rule -a Floating state=floating rectangle=${X3}x${Y3}+${X3}+${Y3}
bspc rule -a Connman-gtk state=floating
bspc rule -a iwgtk state=floating
bspc rule -a discord state=floating rectangle=${X2}x${Y2}+${X4}+${Y4} sticky=on layer=above
bspc rule -a Electron state=floating rectangle=${X2}x${Y2}+${X4}+${Y4} sticky=on layer=above
#bspc rule -a discord state=floating rectangle=${X2}x${Y}+0+0 sticky=on layer=above
bspc rule -a xkcd state=floating

###--Programs---###
#scratchpad discord

###---Fix keyboard--###
xmodmap -e "keycode 112 = Home"
xmodmap -e "keycode 110 = Prior"
xmodmap -e "keycode 117 = End"
xmodmap -e "keycode 115 = Next"

