#! /bin/bash

# You preferably wanna run `sudo su` before this script to be able to execute everything without re-entering root password.

# Get closest mirrors before installing stuff
sudo pacman -Syy
sudo pacman -S reflector
sudo reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist

# Update
sudo pacman -Syyuu
sudo pacman -S --needed git base-devel

git clone --recurse-submodules https://github.com/mradigen/dotfiles.git # Recurse to install submodules like goyo and todo-startpage
cd dotfiles

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
# mv yay ~/.local/share/Trash/files
sudo rm -r yay

# Oh my Zsh
sudo pacman -S zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install EVERYTHING
yay -S --needed - < Documents/Extra/packages

# Copy dotfiles
rsync -r --exclude ".git/" . ~
cp -r .git ~/.dotfiles

# Change execution permissions
chmod +x ~/.config/alacritty/fixtheme.sh
chmod +x ~/.config/bspwm/bspwmrc
chmod +x ~/.config/sxhkd/sxhkdrc
chmod +x ~/.config/polybar/music.sh
chmod +x ~/.config/polybar/mic.sh
chmod +x ~/.local/bin/*

systemctl reboot
