#! /bin/bash

############
### Sudo ###
############
if [[ $EUID -eq 0 ]]; then
    error "Do not run this script as the root user."
    exit 1
fi

sudo -v

# Sudo loop
while sleep 200; do sudo -v; done &
sudoloop=$!
############

# Get closest mirrors before installing stuff
sudo pacman -Syy
sudo pacman -S reflector
sudo reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist

# Update
sudo pacman -Syyuu
sudo pacman -S --needed git base-devel

# Yay
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
cd ..
sudo rm -rf yay-bin

# Oh my Zsh
sudo pacman -S zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# Plugin zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Chaotic AUR
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
sudo pacman -Syy

# Clone dotfiles
git clone --recurse-submodules https://github.com/mradigen/dotfiles.git # Recurse to install submodules like goyo and todo-startpage
cd dotfiles

sudo mv /etc/pacman.conf /etc/pacman.conf.old
sudo cp Documents/Extra/ROOT_DIR/etc/pacman.conf /etc/pacman.conf

# Install EVERYTHING
yay -S --needed --noconfirm - < Documents/Extra/packages

# Copy dotfiles
rsync -r --exclude ".git/" . ~
cp -r .git ~/.dotfiles

# Change execution permissions
cd ~
chmod +x .config/alacritty/fixtheme.sh
chmod +x .config/bspwm/bspwmrc
chmod +x .config/sxhkd/sxhkdrc
chmod +x .config/polybar/music.sh
chmod +x .config/polybar/mic.sh
chmod +x .local/bin/*
chmod +x .fehbg .xinitrc
chmod +x .screenlayout/*.sh

kill "$sudoloop"

#systemctl reboot
